version: '3.6'

services:
  wireguard:
    image: ghcr.io/alexyao2015/wireguard-boringtun:latest
    restart: always
    privileged: true
    sysctls:
      # You may need to uncomment all or some of these
      # - net.ipv4.ip_forward=1
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.all.forwarding=1
      # - net.ipv6.conf.default.forwarding=1
    volumes:
      # You can also bind mount wg0.conf instead
      # - ./wg0.conf:/etc/wireguard/wg0.conf
      - ./testdata/config:/config
      - ./testdata/log:/log
    env_file:
      - ./.env
    ports:
      - "59790:59790/udp"
