#!/command/with-contenv sh
. "/usr/local/bin/logger"
program_name="wireguard-config-patch"

if [[ -f "/etc/wireguard/wg0.conf" ]]; then
  echo "Config detected at /etc/wireguard/wg0.conf" | info
  echo "Using the existing config for configuration" | info
  echo "This ignores all environment variables" | info
  cp /etc/wireguard/wg0.conf /run/wireguard/wg0.conf
fi

# This is so wg-quick doesn't complain about incorrect permissions
echo "Setting permissions of /run/wireguard/wg0.conf..." | info "[${program_name}] "
chmod 600 /run/wireguard/wg0.conf
