#!/command/with-contenv sh
. "/usr/local/bin/logger"
# ==============================================================================
# wireguard
# Bring up wireguard
# ==============================================================================
PATH=/sbin:$PATH

echo "Starting wireguard..." | info

fdmove -c 2 1 \
  /bin/wg-quick up /run/wireguard/wg0.conf

wait "$(pidof boringtun)"
