name: Docker Build

on:
  push:
  release:
    types: [published, prereleased]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Docker Image

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Cache Docker layers
        uses: actions/cache@v2
        continue-on-error: true
        with:
          path: /tmp/.buildx-cache
          key: ${{ github.ref_name }}-${{ github.sha }}
          restore-keys: |
            ${{ github.ref_name }}-
      - name: Build Branch
        run: |
          set -x
          docker build \
            --tag ci:${{ github.run_number }} \
            --progress plain \
            --file ./Dockerfile \
            --cache-from type=local,src=/tmp/.buildx-cache \
            --cache-to type=local,dest=/tmp/.buildx-cache-new,mode=max \
            --load \
            .
      # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
      - name: Inspect
        run: |
          set -x
          docker image inspect ci:${{ github.run_number }}
          docker history --no-trunc ci:${{ github.run_number }}
      - name: Save tarball
        run: |
          set -x
          docker save --output ci-${{ github.run_number }}.tar.gz ci:${{ github.run_number }}
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ci-${{ github.run_number }}
          path: ci-${{ github.run_number }}.tar.gz

  publish:
    needs: build
    name: Publish Image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        registry:
          - {
            url: ghcr.io/alexyao2015,
            username: GCHR_USERNAME,
            password: GHCR_PAT,
            repo: ghcr.io/alexyao2015/wireguard-boringtun
          }
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download container artifact
        uses: actions/download-artifact@v2
        with:
          name: ci-${{ github.run_number }}

      - name: Import image
        run: |
          docker load --input ci-${{ github.run_number }}.tar.gz
      - name: Docker login
        run: |
          docker login ${{ matrix.registry.url }} -u ${{ secrets[matrix.registry.username] }} -p ${{ secrets[matrix.registry.password] }}
      - name: Push image
        if: ${{ github.ref == 'refs/heads/master' }}
        run: |
          ./publish.py \
            --tag ${GITHUB_REF##*/} \
            --repo ${{ matrix.registry.repo }} \
            --image \
            --ci \
            --image-name ci:${{ github.run_number }} \
            --latest
